"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = RootLayout;
exports.metadata = void 0;
var _google = require("next/font/google");
require("./globals.css");
var geistSans = (0, _google.Geist)({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});
var geistMono = (0, _google.Geist_Mono)({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});
var metadata = exports.metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};
function RootLayout(_ref) {
  var children = _ref.children;
  return /*#__PURE__*/React.createElement("html", {
    lang: "en"
  }, /*#__PURE__*/React.createElement("body", {
    className: "".concat(geistSans.variable, " ").concat(geistMono.variable)
  }, children));
}